### ISSUE TITLE
Support values with spaces

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-bootvar-xen#6]
The current scheme doesn't work when there are space in the the values. Also it would be nice to not use `Re_str` to do the parsing of arguments :-)

**Comment by dbuenzli** [comment]
Note that one thing I have been realizing recently is that rather than have "key=value" arguments it's much better to have sequences of "key" "value" arguments, it entirely removes the need for quoting and escaping abilities in the `=value` part. It also makes it easier to specify the values in shell script without having to think about the number of levels of quoting you need to apply...

**Comment by hannesm** [comment]
The parser has moved over to https://github.com/mirage/parse-argv, and AFAIK it accepts whitespaces (and `key=value`).  The parser uses `astring` and no longer `Re_str`.  Please open an issue at parse-argv if you're still not satisfied (there's even a test suite in `test.ml`).
